### ISSUE TITLE
No such file in repo: src/requirements.txt 

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [mrkprdo/webdriver_manager_test#1]
There is no such file in repo, but dockerfile needs src/requirements.txt to have been built.
https://github.com/mrkprdo/webdriver_manager_test/blob/c82a91d9d4b418481734943c1c92afab419249b4/dockerfile#L11

**Comment by mrkprdo** [comment]
lol, forgot that gitignore adds it automatically.
added now.

**Comment by aleksandr-kotlyar** [comment]
Thank you :)
